import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import JSZip from "jszip";

export async function GET(
  _request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const agent = await db.agent.findUnique({
      where: { id: params.id },
      include: {
        versions: { orderBy: { createdAt: "desc" }, take: 1 },
        memories: {
          include: {
            collection: {
              select: { id: true, name: true, description: true, chromaId: true },
            },
          },
        },
        tools: true,
        skills: true,
      },
    });

    if (!agent) {
      return NextResponse.json({ error: "Agent not found" }, { status: 404 });
    }

    const latestVersion = agent.versions[0];
    const definition = latestVersion
      ? JSON.parse(latestVersion.definition)
      : {};

    const agentSlug = agent.name.toLowerCase().replace(/\s+/g, "-");
    const versionStr = latestVersion?.version || "v0.1.0";

    // Build integrations metadata for the package
    const integrations = {
      tools: (agent.tools || []).map((t) => ({
        toolId: t.toolId,
        config: t.config ? JSON.parse(t.config) : {},
      })),
      skills: (agent.skills || []).map((s) => ({
        skillId: s.skillId,
      })),
      memory: (agent.memories || []).map((m) => ({
        collectionName: m.collection.name,
        collectionDescription: m.collection.description,
        chromaId: m.collection.chromaId,
      })),
    };

    const manifest = {
      name: agent.name,
      version: versionStr,
      description: agent.description,
      sdkVersion: ">=0.1.0",
      createdAt: new Date().toISOString(),
      tags: JSON.parse(agent.tags || "[]"),
      integrations,
    };

    const packageJson = {
      name: `${agentSlug}-agent`,
      version: versionStr.replace(/^v/, ""),
      description: agent.description,
      main: "src/index.ts",
      scripts: {
        start: "npx tsx src/index.ts",
      },
      dependencies: {
        "@anthropic-ai/sdk": "^0.39.0",
      },
      devDependencies: {
        tsx: "^4.0.0",
      },
    };

    const indexTs = `import Anthropic from "@anthropic-ai/sdk";

const client = new Anthropic();

const AGENT_DEFINITION = ${JSON.stringify(definition, null, 2)};

async function main() {
  const prompt = process.argv[2] || "Hello!";

  const response = await client.messages.create({
    model: AGENT_DEFINITION.model || "claude-sonnet-4-6",
    max_tokens: 4096,
    system: AGENT_DEFINITION.systemPrompt || "",
    messages: [{ role: "user", content: prompt }],
  });

  for (const block of response.content) {
    if (block.type === "text") {
      console.log(block.text);
    }
  }
}

main().catch(console.error);
`;

    // Build integrations section for README
    const toolNames = integrations.tools.map((t) => t.toolId).join(", ");
    const skillNames = integrations.skills.map((s) => s.skillId).join(", ");
    const memoryNames = integrations.memory.map((m) => m.collectionName).join(", ");

    let integrationsDoc = "";
    if (integrations.tools.length > 0 || integrations.skills.length > 0 || integrations.memory.length > 0) {
      integrationsDoc = `\n## Integrations\n`;
      if (integrations.tools.length > 0) {
        integrationsDoc += `\n### Tools\n${toolNames}\n`;
      }
      if (integrations.skills.length > 0) {
        integrationsDoc += `\n### Skills\n${skillNames}\n`;
      }
      if (integrations.memory.length > 0) {
        integrationsDoc += `\n### Memory Collections\n${memoryNames}\n`;
      }
    }

    const readme = `# ${agent.name}

${agent.description || "An AI agent built with Claude."}

## Version
${versionStr}

## Quick Start

\`\`\`bash
npm install
export ANTHROPIC_API_KEY=your-key-here
npm start "Your prompt here"
\`\`\`

## Configuration

The agent definition is in \`agent-definition.json\`. You can modify the system prompt, model, temperature, and tools.
${integrationsDoc}
## Generated by Maestro Agentica
This agent package was exported from the Maestro Agentica platform.
`;

    // Create ZIP file
    const zip = new JSZip();
    const folder = zip.folder(`${agentSlug}-agent`)!;

    folder.file("manifest.json", JSON.stringify(manifest, null, 2));
    folder.file("agent-definition.json", JSON.stringify(definition, null, 2));
    folder.file("package.json", JSON.stringify(packageJson, null, 2));
    folder.file("README.md", readme);
    folder.file("src/index.ts", indexTs);

    const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });

    return new NextResponse(zipBuffer as unknown as BodyInit, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${agentSlug}-agent.zip"`,
      },
    });
  } catch (error) {
    console.error("Export error:", error);
    return NextResponse.json(
      { error: "Failed to export agent" },
      { status: 500 }
    );
  }
}
